version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "github.com/external-secrets/external-secrets"
        update-types: ["version-update:semver-major"]
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-major"]
    groups:
      kube:
        patterns:
          - k8s.io/*
          - sigs.k8s.io/*
      istio:
        patterns:
          - istio.io/*
          - github.com/istio/*
      flux:
        patterns:
          - fluxcd.io/*
          - github.com/fluxcd/*
      argo:
        patterns:
          - argoproj.io/*
          - github.com/argoproj/*
      external-secrets:
        patterns:
          - github.com/external-secrets/*
          - github.com/external-secrets/external-secrets/*
      tanzu:
        patterns:
          - github.com/vmware-tanzu/*
      linkerd:
        patterns:
          - github.com/linkerd/*
      cert-manager:
        patterns:
          - github.com/cert-manager/*
      other:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
